# permissions for end users to view mysqlhas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysqlha-viewer-role
rules:
- apiGroups:
  - paasapp.emergen.cn
  resources:
  - mysqlhas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - paasapp.emergen.cn
  resources:
  - mysqlhas/status
  verbs:
  - get
