
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - paasapp.emergen.cn
  resources:
  - mysqlhas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - paasapp.emergen.cn
  resources:
  - mysqlhas/finalizers
  verbs:
  - update
- apiGroups:
  - paasapp.emergen.cn
  resources:
  - mysqlhas/status
  verbs:
  - get
  - patch
  - update
